id: P001659
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20462
  title: བོད་ལྗོངས་ཡུལ་སྐོར་སྣེ་ཤན
  author: ''
  volumes:
    016cd9875f634201b16fae69e05a9035:
      image_group_id: I4691
      title: ''
      volume_number: 1
      total_pages: 266
      base_file: v001.txt
